# Generated by Django 3.0.3 on 2020-02-20 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coder_yet', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='script',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='script',
            name='image',
            field=models.ImageField(blank=True, upload_to='myscripts/'),
        ),
        migrations.AddField(
            model_name='script',
            name='input',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='script',
            name='make_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='script',
            name='output',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='script',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='script',
            name='working_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='script',
            name='url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='myproblems/')),
                ('discipline', models.CharField(max_length=50)),
                ('make_public', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Coder')),
            ],
        ),
        migrations.AddField(
            model_name='script',
            name='coder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.Coder'),
        ),
        migrations.AddField(
            model_name='script',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='share.Problem'),
        ),
    ]
